# PATH: .github/workflows/ci.yaml
name: CI/CD

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup and Build
        uses: ./.github/actions/setup-and-build

      - name: Run Prettier check
        run: pnpm run format:check

      - name: Run ESLint
        run: pnpm run lint

      - name: Run type check
        run: pnpm run typecheck

      - name: Run tests
        run: pnpm run test
